languageCode = "en-us"
title = "The Forge"
baseURL = "http://forgeutah.tech/"
theme = "imperfect-slim"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true


[Params]
	logo = "img/logo.png"
	subtitle = "Helping Utah technologists share, learn, and build"
	rss = true
  comments = true
  dateFormat = "January 2, 2006"


[Author]
  name = "Clint Berry"
  github = "utahforge"
  twitter = "@forgeutah"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Meetups"
    url = "/meetups/"
<<<<<<< HEAD
    weight = 3  
=======
    weight = 3

[[menu.main]]
    name = "Sponsors"
    url = "/sponsors/"
    weight = 3
>>>>>>> e6172520018922f4cdfffd5a6e0dea53c2653d39
